### ISSUE TITLE
After local compilation and packaging, the error is reported during execution, and the error message is

### ISSUE THREAD

**Issue by chkch** [opendiffy/diffy#18]
The following is a detailed error message, please help me, is it wrong with my packaged order: sbt ~package

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/twitter/app/Flags
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.twitter.app.Flags
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by puneetkhanduri** [comment]
What command are you running to get this output?

**Comment by puneetkhanduri** [comment]
Side: Unless you want to make changes to Diffy's code, you no longer have to build Diffy.

We have released the latest built jar [here](https://github.com/opendiffy/diffy/releases/latest).
Alternatively, you can also use the [docker image](https://hub.docker.com/r/diffy/diffy).

**Comment by chkch** [comment]
@puneetkhanduri Hey, I executed the command sbt ~package to get the above error message.

**Comment by chkch** [comment]
Thank you very much for your answer. I have realized that the command I executed has an error. The correct command should be ./sbt assembly
