### ISSUE TITLE
Several errors while executing mainly: java.lang.IllegalArgumentException: requirement failed: You must specify host and port in hosts: localhost:50120:443

### ISSUE THREAD

**Issue by starx** [opendiffy/diffy#47]
I am not able to get this to work at all. 

First of all, curl response header below will indicate that my services are working.

```bash
$ curl -IsSk https://localhost:50111

HTTP/1.1 200 OK
Date: Tue, 14 Jul 2020 03:49:31 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Last-Modified: Thu, 19 Mar 2020 12:46:05 GMT
ETag: "1b3-5a1348d58c64f"
Accept-Ranges: bytes
Content-Length: 435
Vary: Accept-Encoding
Cache-Control: max-age=2592000
Expires: Thu, 13 Aug 2020 03:49:31 GMT
Connection: close
Content-Type: text/html; charset=UTF-8


$ curl -IsSk https://localhost:50120


HTTP/1.1 200 OK
Date: Tue, 14 Jul 2020 03:49:50 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Last-Modified: Thu, 19 Mar 2020 12:47:14 GMT
ETag: "1b3-5a13491710daf"
Accept-Ranges: bytes
Content-Length: 435
Vary: Accept-Encoding
Cache-Control: max-age=2592000
Expires: Thu, 13 Aug 2020 03:49:50 GMT
Connection: close
Content-Type: text/html; charset=UTF-8

$ curl -IsSk https://localhost:50122


HTTP/1.1 200 OK
Date: Tue, 14 Jul 2020 03:49:55 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Last-Modified: Thu, 19 Mar 2020 12:47:14 GMT
ETag: "1b3-5a13491710daf"
Accept-Ranges: bytes
Content-Length: 435
Vary: Accept-Encoding
Cache-Control: max-age=2592000
Expires: Thu, 13 Aug 2020 03:49:55 GMT
Connection: close
Content-Type: text/html; charset=UTF-8
```

I run the diffy instance like this:

```bash
docker run --rm \
  -p 8880:8880 -p 8881:8881 -p 8888:8888 \
  diffy/diffy \
    -candidate=localhost:50111 \
    -master.primary=localhost:50120 \
    -master.secondary=localhost:50122 \
    -responseMode='primary' \
    -service.protocol=https \
    -serviceName="Tier-Service" \
    -proxy.port=:8880 \
    -admin.port=:8881 \
    -http.port=:8888 \
    -rootUrl=localhost:8888 \
    -summary.email='test@email.com' \
    -summary.delay="5"
```
Please note that I am not running on daemon mode.  The command above outputs the following lines in the logs.

```text
03:55:35.532 [main] INFO com.twitter.util.logging.Slf4jBridgeUtility$ - org.slf4j.bridge.SLF4JBridgeHandler installed.
03:55:37.399 [main] INFO ai.diffy.Main$ - Process started
03:55:38.291 [main] INFO ai.diffy.Main$ - Serving admin http on 0.0.0.0/0.0.0.0:8881
03:55:42.513 [main] WARN com.twitter.finagle.util.DefaultTimer - Can not service-load a timer. Using JavaTimer instead.
03:55:42.538 [main] INFO com.twitter.finagle - Finagle version 19.8.0 (rev=91a366ca88ba7231eeced7987f3835ff1eb0a0c1) built at 20190805-173757
03:55:48.836 [main] WARN ai.diffy.DiffyServiceModule$ - Malformed resource mapping: [Ljava.lang.String;@48c4245d. Should be <pattern>;<resource-name>
03:55:50.794 [main] INFO com.twitter.finagle - candidate: name resolution failed  (local dtab: Dtab())
java.lang.IllegalArgumentException: requirement failed: You must specify host and port in hosts: localhost:50111:443
        at scala.Predef$.require(Predef.scala:281)
        at com.twitter.finagle.util.InetSocketAddressUtil$.$anonfun$parseHostPorts$3(InetSocketAddressUtil.scala:38)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at scala.collection.TraversableLike.map(TraversableLike.scala:237)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
        at com.twitter.finagle.util.InetSocketAddressUtil$.parseHostPorts(InetSocketAddressUtil.scala:37)
        at com.twitter.finagle.InetResolver.$anonfun$bind$1(InetResolver.scala:166)
        at com.twitter.util.Try$.apply(Try.scala:26)
        at com.twitter.finagle.InetResolver.bind(InetResolver.scala:166)
        at com.twitter.finagle.BaseResolver.eval(Resolver.scala:171)
        at com.twitter.finagle.Client.newService(Client.scala:48)
        at com.twitter.finagle.Client.newService$(Client.scala:47)
        at com.twitter.finagle.Http$Client.newService(Http.scala:184)
        at ai.diffy.proxy.SimpleHttpsDifferenceProxy.serviceFactory(HttpDifferenceProxy.scala:108)
        at ai.diffy.proxy.SimpleHttpsDifferenceProxy.serviceFactory(HttpDifferenceProxy.scala:88)
        at ai.diffy.proxy.DifferenceProxy.$init$(DifferenceProxy.scala:57)
        at ai.diffy.proxy.SimpleHttpsDifferenceProxy.<init>(HttpDifferenceProxy.scala:93)
        at ai.diffy.proxy.DifferenceProxyModule$.providesDifferenceProxy(DifferenceProxy.scala:30)
        at ai.diffy.proxy.DifferenceProxyModule$$$FastClassByGuice$$16957c87.invoke(<generated>)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
        at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
        at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at com.twitter.inject.app.internal.InstalledModules$.create(InstalledModules.scala:38)
        at com.twitter.inject.app.App.loadModules(App.scala:146)
        at com.twitter.inject.app.App.loadModules$(App.scala:141)
        at ai.diffy.MainService.loadModules(Main.scala:10)
        at com.twitter.inject.app.App.main(App.scala:55)
        at com.twitter.inject.app.App.main$(App.scala:54)
        at com.twitter.inject.server.TwitterServer.main(TwitterServer.scala:173)
        at com.twitter.inject.server.TwitterServer.main$(TwitterServer.scala:172)
        at ai.diffy.MainService.main(Main.scala:10)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.twitter.app.App.$anonfun$nonExitingMain$4(App.scala:364)
        at scala.Option.foreach(Option.scala:274)
        at com.twitter.app.App.nonExitingMain(App.scala:363)
        at com.twitter.app.App.nonExitingMain$(App.scala:344)
        at ai.diffy.MainService.nonExitingMain(Main.scala:10)
        at com.twitter.app.App.main(App.scala:333)
        at com.twitter.app.App.main$(App.scala:331)
        at ai.diffy.MainService.main(Main.scala:10)
        at ai.diffy.Main.main(Main.scala)
03:55:50.968 [main] INFO com.twitter.finagle - primary: name resolution failed  (local dtab: Dtab())
java.lang.IllegalArgumentException: requirement failed: You must specify host and port in hosts: localhost:50120:443
        at scala.Predef$.require(Predef.scala:281)
        at com.twitter.finagle.util.InetSocketAddressUtil$.$anonfun$parseHostPorts$3(InetSocketAddressUtil.scala:38)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at scala.collection.TraversableLike.map(TraversableLike.scala:237)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
        at com.twitter.finagle.util.InetSocketAddressUtil$.parseHostPorts(InetSocketAddressUtil.scala:37)
        at com.twitter.finagle.InetResolver.$anonfun$bind$1(InetResolver.scala:166)
        at com.twitter.util.Try$.apply(Try.scala:26)
        at com.twitter.finagle.InetResolver.bind(InetResolver.scala:166)
        at com.twitter.finagle.BaseResolver.eval(Resolver.scala:171)
        at com.twitter.finagle.Client.newService(Client.scala:48)
        at com.twitter.finagle.Client.newService$(Client.scala:47)
        at com.twitter.finagle.Http$Client.newService(Http.scala:184)
        at ai.diffy.proxy.SimpleHttpsDifferenceProxy.serviceFactory(HttpDifferenceProxy.scala:108)
        at ai.diffy.proxy.SimpleHttpsDifferenceProxy.serviceFactory(HttpDifferenceProxy.scala:88)
        at ai.diffy.proxy.DifferenceProxy.$init$(DifferenceProxy.scala:58)
        at ai.diffy.proxy.SimpleHttpsDifferenceProxy.<init>(HttpDifferenceProxy.scala:93)
        at ai.diffy.proxy.DifferenceProxyModule$.providesDifferenceProxy(DifferenceProxy.scala:30)
        at ai.diffy.proxy.DifferenceProxyModule$$$FastClassByGuice$$16957c87.invoke(<generated>)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
        at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
        at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at com.twitter.inject.app.internal.InstalledModules$.create(InstalledModules.scala:38)
        at com.twitter.inject.app.App.loadModules(App.scala:146)
        at com.twitter.inject.app.App.loadModules$(App.scala:141)
        at ai.diffy.MainService.loadModules(Main.scala:10)
        at com.twitter.inject.app.App.main(App.scala:55)
        at com.twitter.inject.app.App.main$(App.scala:54)
        at com.twitter.inject.server.TwitterServer.main(TwitterServer.scala:173)
        at com.twitter.inject.server.TwitterServer.main$(TwitterServer.scala:172)
        at ai.diffy.MainService.main(Main.scala:10)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.twitter.app.App.$anonfun$nonExitingMain$4(App.scala:364)
        at scala.Option.foreach(Option.scala:274)
        at com.twitter.app.App.nonExitingMain(App.scala:363)
        at com.twitter.app.App.nonExitingMain$(App.scala:344)
        at ai.diffy.MainService.nonExitingMain(Main.scala:10)
        at com.twitter.app.App.main(App.scala:333)
        at com.twitter.app.App.main$(App.scala:331)
        at ai.diffy.MainService.main(Main.scala:10)
        at ai.diffy.Main.main(Main.scala)
03:55:51.028 [main] INFO com.twitter.finagle - secondary: name resolution failed  (local dtab: Dtab())
java.lang.IllegalArgumentException: requirement failed: You must specify host and port in hosts: localhost:50122:443
        at scala.Predef$.require(Predef.scala:281)
        at com.twitter.finagle.util.InetSocketAddressUtil$.$anonfun$parseHostPorts$3(InetSocketAddressUtil.scala:38)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at scala.collection.TraversableLike.map(TraversableLike.scala:237)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
        at com.twitter.finagle.util.InetSocketAddressUtil$.parseHostPorts(InetSocketAddressUtil.scala:37)
        at com.twitter.finagle.InetResolver.$anonfun$bind$1(InetResolver.scala:166)
        at com.twitter.util.Try$.apply(Try.scala:26)
        at com.twitter.finagle.InetResolver.bind(InetResolver.scala:166)
        at com.twitter.finagle.BaseResolver.eval(Resolver.scala:171)
        at com.twitter.finagle.Client.newService(Client.scala:48)
        at com.twitter.finagle.Client.newService$(Client.scala:47)
        at com.twitter.finagle.Http$Client.newService(Http.scala:184)
        at ai.diffy.proxy.SimpleHttpsDifferenceProxy.serviceFactory(HttpDifferenceProxy.scala:108)
        at ai.diffy.proxy.SimpleHttpsDifferenceProxy.serviceFactory(HttpDifferenceProxy.scala:88)
        at ai.diffy.proxy.DifferenceProxy.$init$(DifferenceProxy.scala:59)
        at ai.diffy.proxy.SimpleHttpsDifferenceProxy.<init>(HttpDifferenceProxy.scala:93)
        at ai.diffy.proxy.DifferenceProxyModule$.providesDifferenceProxy(DifferenceProxy.scala:30)
        at ai.diffy.proxy.DifferenceProxyModule$$$FastClassByGuice$$16957c87.invoke(<generated>)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
        at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
        at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at com.twitter.inject.app.internal.InstalledModules$.create(InstalledModules.scala:38)
        at com.twitter.inject.app.App.loadModules(App.scala:146)
        at com.twitter.inject.app.App.loadModules$(App.scala:141)
        at ai.diffy.MainService.loadModules(Main.scala:10)
        at com.twitter.inject.app.App.main(App.scala:55)
        at com.twitter.inject.app.App.main$(App.scala:54)
        at com.twitter.inject.server.TwitterServer.main(TwitterServer.scala:173)
        at com.twitter.inject.server.TwitterServer.main$(TwitterServer.scala:172)
        at ai.diffy.MainService.main(Main.scala:10)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.twitter.app.App.$anonfun$nonExitingMain$4(App.scala:364)
        at scala.Option.foreach(Option.scala:274)
        at com.twitter.app.App.nonExitingMain(App.scala:363)
        at com.twitter.app.App.nonExitingMain$(App.scala:344)
        at ai.diffy.MainService.nonExitingMain(Main.scala:10)
        at com.twitter.app.App.main(App.scala:333)
        at com.twitter.app.App.main$(App.scala:331)
        at ai.diffy.MainService.main(Main.scala:10)
        at ai.diffy.Main.main(Main.scala)
03:55:51.474 [main] INFO ai.diffy.Main$ - Resolving Finagle clients before warmup
03:55:51.510 [main] INFO com.twitter.finagle - candidate resolved to Failed(java.lang.IllegalArgumentException: requirement failed: You must specify host
and port in hosts: localhost:50111:443)
03:55:51.515 [main] INFO com.twitter.finagle - primary resolved to Failed(java.lang.IllegalArgumentException: requirement failed: You must specify host an
d port in hosts: localhost:50120:443)
03:55:51.520 [main] INFO com.twitter.finagle - secondary resolved to Failed(java.lang.IllegalArgumentException: requirement failed: You must specify host
and port in hosts: localhost:50122:443)
03:55:51.544 [main] INFO ai.diffy.Main$ - Done resolving clients: [candidate, primary, secondary].
03:55:52.092 [main] INFO ai.diffy.workflow.Workflow - Scheduling ai.diffy.workflow.FunctionalReport at 2020-07-14 03:55:52 +0000
03:56:00.990 [main] INFO com.twitter.finatra.http.routing.HttpRouter - Adding routes
GET     /api/1/overview
GET     /api/1/report
GET     /api/1/endpoints
GET     /api/1/endpoints/:endpoint/stats
GET     /api/1/endpoints/:endpoint/fields/:path/results
GET     /api/1/endpoints/:endpoint/fields/:path/results/:index
GET     /api/1/requests/:id
GET     /api/1/clear
POST    /api/1/email
GET     /api/1/info
GET     /
GET     /css/:*
GET     /scripts/:*
03:56:01.035 [main] INFO ai.diffy.Main$ - Warming up.
03:56:01.434 [main] INFO ai.diffy.Main$ - http server started on port: 0.0.0.0/0.0.0.0:8888
03:56:01.445 [main] INFO ai.diffy.Main$ - admin http server started on port 8881
03:56:01.472 [main] INFO ai.diffy.Main$ - diffy started.
03:56:01.473 [main] INFO ai.diffy.Main$ - Startup complete, server awaiting.
03:56:01.477 [main] INFO com.twitter.inject.server.Awaiter$ - Awaiting 2 awaitables:
com.twitter.finagle.server.ListeningStackServer$$anon$1
com.twitter.finagle.server.ListeningStackServer$$anon$1
```
Although it mentions `Startup complete` You can see from the output that there were several errors (extracted below) (P.S a side question, why does the log indicate that it is adding some different routes?)

```text
03:55:42.513 [main] WARN com.twitter.finagle.util.DefaultTimer - Can not service-load a timer. Using JavaTimer instead.
03:55:51.028 [main] INFO com.twitter.finagle - secondary: name resolution failed  (local dtab: Dtab())
java.lang.IllegalArgumentException: requirement failed: You must specify host and port in hosts: localhost:50122:443
03:55:51.510 [main] INFO com.twitter.finagle - candidate resolved to Failed(java.lang.IllegalArgumentException: requirement failed: You must specify host
and port in hosts: localhost:50111:443)
03:55:51.515 [main] INFO com.twitter.finagle - primary resolved to Failed(java.lang.IllegalArgumentException: requirement failed: You must specify host an
d port in hosts: localhost:50120:443)
03:55:51.520 [main] INFO com.twitter.finagle - secondary resolved to Failed(java.lang.IllegalArgumentException: requirement failed: You must specify host
```

Now, doing the following curl

```bash
curl http://localhost:8880
```

outputs the following in the log.

```text
04:00:33.273 [finagle/netty4-2-3] WARN com.twitter.finagle.util.DefaultMonitor - Exception propagated to the default monitor (upstream address: /172.17.0.
1:40082, downstream address: n/a, label: ).
java.lang.IllegalArgumentException: requirement failed: You must specify host and port in hosts: localhost:50120:443
        at scala.Predef$.require(Predef.scala:281)
        at com.twitter.finagle.util.InetSocketAddressUtil$.$anonfun$parseHostPorts$3(InetSocketAddressUtil.scala:38)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at scala.collection.TraversableLike.map(TraversableLike.scala:237)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
        at com.twitter.finagle.util.InetSocketAddressUtil$.parseHostPorts(InetSocketAddressUtil.scala:37)
        at com.twitter.finagle.InetResolver.$anonfun$bind$1(InetResolver.scala:166)
        at com.twitter.util.Try$.apply(Try.scala:26)
        at com.twitter.finagle.InetResolver.bind(InetResolver.scala:166)
        at com.twitter.finagle.BaseResolver.eval(Resolver.scala:171)
        at com.twitter.finagle.Client.newService(Client.scala:48)
        at com.twitter.finagle.Client.newService$(Client.scala:47)
        at com.twitter.finagle.Http$Client.newService(Http.scala:184)
        at ai.diffy.proxy.SimpleHttpsDifferenceProxy.serviceFactory(HttpDifferenceProxy.scala:108)
        at ai.diffy.proxy.SimpleHttpsDifferenceProxy.serviceFactory(HttpDifferenceProxy.scala:88)
        at ai.diffy.proxy.DifferenceProxy.$init$(DifferenceProxy.scala:58)
        at ai.diffy.proxy.SimpleHttpsDifferenceProxy.<init>(HttpDifferenceProxy.scala:93)
        at ai.diffy.proxy.DifferenceProxyModule$.providesDifferenceProxy(DifferenceProxy.scala:30)
        at ai.diffy.proxy.DifferenceProxyModule$$$FastClassByGuice$$16957c87.invoke(<generated>)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
        at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
        at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at com.twitter.inject.app.internal.InstalledModules$.create(InstalledModules.scala:38)
        at com.twitter.inject.app.App.loadModules(App.scala:146)
        at com.twitter.inject.app.App.loadModules$(App.scala:141)
        at ai.diffy.MainService.loadModules(Main.scala:10)
        at com.twitter.inject.app.App.main(App.scala:55)
        at com.twitter.inject.app.App.main$(App.scala:54)
        at com.twitter.inject.server.TwitterServer.main(TwitterServer.scala:173)
        at com.twitter.inject.server.TwitterServer.main$(TwitterServer.scala:172)
        at ai.diffy.MainService.main(Main.scala:10)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.twitter.app.App.$anonfun$nonExitingMain$4(App.scala:364)
        at scala.Option.foreach(Option.scala:274)
        at com.twitter.app.App.nonExitingMain(App.scala:363)
        at com.twitter.app.App.nonExitingMain$(App.scala:344)
        at ai.diffy.MainService.nonExitingMain(Main.scala:10)
        at com.twitter.app.App.main(App.scala:333)
        at com.twitter.app.App.main$(App.scala:331)
        at ai.diffy.MainService.main(Main.scala:10)
        at ai.diffy.Main.main(Main.scala)
```

I tried on the https as well, which gives the following error. So although my app is served over https it seems to still use http to initiate the propagation.

```bash
$ curl -k https://localhost:8880


curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

**Comment by puneetkhanduri** [comment]
@starx : Please use quotes around all 3 network addresses like so `'localhost:50111'` instead of `localhost:50111`.

**Comment by starx** [comment]
@puneetkhanduri I tried both single and double quotes. No difference in the logs.

**Comment by puneetkhanduri** [comment]
Never mind. I didn't look at your configuration closely enough. The problem has to do how we deal with https ports - which is not the right way. Let me work on a fix and update this issue when resolved.

**Comment by starx** [comment]
Is it fixed?

**Comment by starx** [comment]
@puneetkhanduri Is this issue fixed?
