### ISSUE TITLE
Exception propagated to the default monitor  

### ISSUE THREAD

**Issue by Linxi-brave** [opendiffy/diffy#53]
I run my Diffy jar .The develop Diffy script :

java -jar /Users/huangwenjiao/.Trash/diffy/diffy/target/scala-2.12/diffy-server.jar \
-candidate= 'testdnapp.bitkinetic.com:9052' \
-master.primary= 'devdnapp.bitkinetic.com:9052' \
-master.secondary= 'prednapp.bitkinetic.com:9052' \
-service.protocol=https \
-serviceName=My-Service \
-proxy.port=:8780 \
-admin.port=:8781 \
-http.port=:8789 \
-rootUrl='localhost:8789' \
-summary.email="hwj@insucrm.com"

And I can open http：//localhost:8770 in my browser.
But when I send my resquest ,it shown Exception propagated to the default monitor .And there is nothing difference in http：//localhost:877 .
Exception propagated to the default monitor (upstream address: /127.0.0.1:56232, downstream address: n/a, label: ).
ai.diffy.proxy.DifferenceProxy$NoResponseException$: No responses provided by diffy
	at ai.diffy.proxy.DifferenceProxy$NoResponseException$.<clinit>(DifferenceProxy.scala)
	at ai.diffy.proxy.DifferenceProxy$.<init>(DifferenceProxy.scala:36)
	at ai.diffy.proxy.DifferenceProxy$.<clinit>(DifferenceProxy.scala)
	at ai.diffy.proxy.SimpleHttpDifferenceProxy$.$anonfun$httpSideEffectsFilter$1(HttpDifferenceProxy.scala:59)
	at com.twitter.finagle.Filter$$anon$16.apply(Filter.scala:406)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:93)
	at com.twitter.finagle.ServiceProxy.apply(ServiceProxy.scala:12)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.tracing.AnnotatingTracingFilter.apply(TraceInitializerFilter.scala:140)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:93)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.tracing.ServerDestTracingFilter.apply(DestinationTracing.scala:38)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:93)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.service.DeadlineFilter.apply(DeadlineFilter.scala:265)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:93)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.filter.ExceptionSourceFilter.apply(ExceptionSourceFilter.scala:50)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:93)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.filter.MkJvmFilter$$anon$1.apply(MkJvmFilter.scala:30)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:93)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.tracing.AnnotatingTracingFilter.apply(TraceInitializerFilter.scala:140)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:93)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.http.filter.HttpNackFilter.$anonfun$apply$1(HttpNackFilter.scala:159)
	at com.twitter.util.Local.let(Local.scala:4979)
	at com.twitter.finagle.context.LocalContext.letLocal(LocalContext.scala:53)
	at com.twitter.finagle.context.LocalContext.let(LocalContext.scala:24)
	at com.twitter.finagle.http.filter.HttpNackFilter.apply(HttpNackFilter.scala:159)
	at com.twitter.finagle.http.filter.HttpNackFilter.apply(HttpNackFilter.scala:113)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:93)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.http.filter.PayloadSizeFilter.apply(PayloadSizeFilter.scala:123)
	at com.twitter.finagle.http.filter.PayloadSizeFilter.apply(PayloadSizeFilter.scala:47)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:93)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.server.BackupRequest$$anon$1$$anon$2.apply(BackupRequest.scala:31)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:93)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.http.filter.ServerContextFilter.$anonfun$apply$1(ContextFilter.scala:15)
	at com.twitter.util.Local.let(Local.scala:4979)
	at com.twitter.finagle.context.MarshalledContext.letLocal(MarshalledContext.scala:157)
	at com.twitter.finagle.context.MarshalledContext.let(MarshalledContext.scala:104)
	at com.twitter.finagle.http.codec.HttpContext$.read(HttpContext.scala:90)
	at com.twitter.finagle.http.filter.ServerContextFilter.apply(ContextFilter.scala:15)
	at com.twitter.finagle.http.filter.ServerContextFilter.apply(ContextFilter.scala:12)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:93)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:13)
	at com.twitter.finagle.http.HttpServerTraceInitializer.$anonfun$make$3(HttpServerTraceInitializer.scala:20)
	at com.twitter.finagle.http.TraceInfo$.$anonfun$letTraceIdFromRequestHeaders$1(TraceInfo.scala:105)
	at com.twitter.util.Local.let(Local.scala:4979)
	at com.twitter.finagle.context.MarshalledContext.letLocal(MarshalledContext.scala:157)
	at com.twitter.finagle.context.MarshalledContext.let(MarshalledContext.scala:90)
	at com.twitter.finagle.tracing.Trace$.letId(Trace.scala:104)
	at com.twitter.finagle.http.TraceInfo$.letTraceIdFromRequestHeaders(TraceInfo.scala:103)
	at com.twitter.finagle.http.HttpServerTraceInitializer.$anonfun$make$2(HttpServerTraceInitializer.scala:20)
	at com.twitter.util.Local.let(Local.scala:4979)
	at com.twitter.finagle.context.LocalContext.letLocal(LocalContext.scala:53)
	at com.twitter.finagle.context.LocalContext.let(LocalContext.scala:24)
	at com.twitter.finagle.tracing.Trace$.letTracer(Trace.scala:124)
	at com.twitter.finagle.http.HttpServerTraceInitializer.$anonfun$make$1(HttpServerTraceInitializer.scala:20)
	at com.twitter.finagle.Filter$$anon$16.apply(Filter.scala:406)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:93)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.filter.MonitorFilter.apply(MonitorFilter.scala:66)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:93)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.http.filter.DtabFilter.apply(DtabFilter.scala:25)
	at com.twitter.finagle.http.filter.DtabFilter.apply(DtabFilter.scala:12)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:93)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.http.codec.ResponseConformanceFilter$.apply(ResponseConformanceFilter.scala:23)
	at com.twitter.finagle.http.codec.ResponseConformanceFilter$.apply(ResponseConformanceFilter.scala:18)
	at com.twitter.finagle.Filter$$anon$1.apply(Filter.scala:93)
	at com.twitter.finagle.http.codec.HttpServerDispatcher.dispatch(HttpServerDispatcher.scala:42)
	at com.twitter.finagle.http.codec.HttpServerDispatcher.dispatch(HttpServerDispatcher.scala:23)
	at com.twitter.finagle.http.exp.GenStreamingSerialServerDispatcher.$anonfun$dispatchAndHandleFn$2(GenStreamingSerialServerDispatcher.scala:79)
	at com.twitter.util.Local.let(Local.scala:4979)
	at com.twitter.finagle.context.LocalContext.letLocal(LocalContext.scala:53)
	at com.twitter.finagle.context.LocalContext.let(LocalContext.scala:24)
	at com.twitter.finagle.http.exp.GenStreamingSerialServerDispatcher.$anonfun$dispatchAndHandleFn$1(GenStreamingSerialServerDispatcher.scala:77)
	at com.twitter.util.Future.$anonfun$flatMap$1(Future.scala:1798)
	at com.twitter.util.Promise$FutureTransformer.liftedTree1$1(Promise.scala:250)
	at com.twitter.util.Promise$FutureTransformer.k(Promise.scala:250)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:225)
	at com.twitter.util.Promise$WaitQueue.com$twitter$util$Promise$WaitQueue$$run(Promise.scala:101)
	at com.twitter.util.Promise$WaitQueue$$anon$1.run(Promise.scala:96)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:167)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:126)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:243)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:78)
	at com.twitter.util.Promise$WaitQueue.runInScheduler(Promise.scala:96)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:797)
	at com.twitter.util.Promise.update(Promise.scala:769)
	at com.twitter.util.Promise.setValue(Promise.scala:745)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:123)
	at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$2.channelRead(ChannelTransport.scala:169)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at com.twitter.finagle.netty4.http.handler.UnpoolHttpHandler$.channelRead(UnpoolHttpHandler.scala:32)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at com.twitter.finagle.netty4.http.handler.BadRequestHandler.channelRead(BadRequestHandler.scala:41)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at com.twitter.finagle.netty4.http.handler.HeaderValidatorHandler$.channelRead(HeaderValidatorHandler.scala:51)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at com.twitter.finagle.netty4.http.handler.UriValidatorHandler$.channelRead(UriValidatorHandler.scala:29)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Linxi-brave** [comment]
My test request script :
# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/tklogin.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseTklogin(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/api/v5/login/mplogin")
            .post("http://localhost:8780/api/v5/login/mplogin")
            .with_headers(
                **{
                    "lang": "CN",
                    "User-Agent": "TeamKit/3.6.5 (iPhone; iOS 13.6; Scale/2.00)",
                    "r": "a79e7f71872944a59df618ad744cc608",
                    "teamrole": "0",
                    "d-tk": "",
                    "t": "1602468760",
                    "version": "3.6.5",
                    "Content-Length": "58",
                    "sign": "1140892160",
                    "Connection": "keep-alive",
                    "d-version": "41",
                    "DeviceModel": "iPhone12,1",
                    "Accept-Language": "zh-Hans-CN;q=1, zh-Hant-HK;q=0.9, en-IN;q=0.8, ja-CN;q=0.7, en-GB;q=0.6, yue-Hant-CN;q=0.5",
                    "d-os": "ios",
                    "Accept": "*/*",
                    "Content-Type": "application/json",
                    "dnapp": "100001",
                    "Accept-Encoding": "gzip, deflate, br",
                    "app": "3001",
                }
            )
            .with_json({"zoneNum": "86", "phone": "15088132074", "password": "123456"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseTklogin().test_start()

**Comment by Linxi-brave** [comment]
你好，邮件已收到，将尽快处理并回复。
