### ISSUE TITLE
Any plan to support macbook M1 chip

### ISSUE THREAD

**Issue by dingxiong** [opendiffy/diffy#68]
The example does not work in macbook M1. Is any plan to support macbook M1 chip?

**Comment by puneetkhanduri** [comment]
We have pushed a fix. Please try the Quickstart example instructions again with the latest master.

Please feel free to reopen this issue with error logs if the issue persists.

**Comment by dingxiong** [comment]
thanks so much!

**Comment by dingxiong** [comment]
Hi @puneetkhanduri ,

I still have issue of running the examples on M1 chip.
The error message is 
```
2022-09-24 12:37:46.440 ERROR 97893 --- [onPool-worker-1] i.n.r.d.DnsServerAddressStreamProviders  : Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.

java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[na:na]
        at io.netty.resolver.dns.DnsServerAddressStreamProviders.<clinit>(DnsServerAddressStreamProviders.java:64) ~[netty-resolver-dns-4.1.79.Final.jar!/:4.1.79.Final]
        at io.netty.resolver.dns.DnsNameResolverBuilder.<init>(DnsNameResolverBuilder.java:60) ~[netty-resolver-dns-4.1.79.Final.jar!/:4.1.79.Final]
        at reactor.netty.transport.NameResolverProvider.newNameResolverGroup(NameResolverProvider.java:479) ~[reactor-netty-core-1.0.22.jar!/:1.0.22]
...
```
I follow this post https://github.com/netty/netty/issues/11020 to fix this issue. I do not know how to add the mac specific dependency in the pom.xml. So I created a new file `pom-mac-arm.xml` and add a dependency 
```
        <dependency>
          <groupId>io.netty</groupId>
          <artifactId>netty-resolver-dns-native-macos</artifactId>
          <version>4.1.82.Final</version>
          <classifier>osx-aarch_64</classifier>
        </dependency>
```
then run `mvn package -f pom-mac-arm.xml`. I feel this is not elegant. You have better idea?

**Comment by puneetkhanduri** [comment]
@dingxiong : Thanks for sharing this solution. We have added the required dependency to the pom file until we find a better solution. This should eliminate the need for you to maintain a separate pom file.
