### ISSUE TITLE
[Help]Diffy API returns 404, while local calls are successful。

### ISSUE THREAD

**Issue by HuaiAnLee** [opendiffy/diffy#88]
### This is my Docker Compose configuration.
```plaintext
  diffy:
    image: diffy/diffy:latest
    ports:
      - "8888:8888"
      - "8880:8880"
#    env_file: "./diffy.env"
    environment:
      candidate: "http://api.pre.myDomain.com"
      master.primary: "http://api.myDomain.com"
      master.secondary: "http://api.myDomain.com"
      responseMode: "candidate"
      service.protocol: "http"
      allowHttpSideEffects: "true"
      serviceName: "Sample Service"
      proxy.port: 8880
      http.port: 8888
      rootUrl: "localhost:8888"
      otel.javaagent.debug: "false"
      otel.metrics.exporter: "none"
      otel.traces.exporter: "jaeger"
      otel.exporter.jaeger.endpoint: "http://tempo:14250"
      otel.exporter.jaeger.traces.endpoint: "http://tempo:14250"
      otel.resource.attributes: "service.name=diffy"
      spring.application.name: "diffy"
      logging.level.web: "INFO"
      logging.level.io.opentelemetry: "WARN"
      logging.level.root: "INFO"
      logging.file.name: "/app/logs/diffy.log"
      logging.file.max-size: "10MB"
      logging.file.max-history: 1
      logging.file.clean-history-on-start: "true"
      spring.mongodb.embedded.version: "4.4.13"
      dockerComposeLocal: "true"
    volumes:
      - ./data/logs:/app/logs
    depends_on:
      - tempo
```

### Description
I'm encountering an issue where the API calls forwarded by Diffy are returning a 404 error, but when I make the same API calls locally, I receive a valid response. Below is the stack trace of the error:

```plaintext
[otel.javaagent 2023-06-05 06:20:35:060 +0000] [ForkJoinPool.commonPool-worker-1] WARN io.opentelemetry.ApiUsageLogging - Instrument name "diffy.noise.POST:api-basicInfo.request.path.NoDifference.differences" is invalid, returning noop instrument. Instrument names must consist of 63 or fewer characters including alphanumeric, _, ., -, and start with a letter.
2023-06-05T06:20:35.060958560Z java.lang.AssertionError
2023-06-05T06:20:35.060961265Z 	at io.opentelemetry.javaagent.shaded.io.opentelemetry.api.internal.ValidationUtil.log(ValidationUtil.java:55)
2023-06-05T06:20:35.060963279Z 	at io.opentelemetry.javaagent.shaded.io.opentelemetry.api.internal.ValidationUtil.checkValidInstrumentName(ValidationUtil.java:72)
2023-06-05T06:20:35.060965222Z 	at io.opentelemetry.javaagent.shaded.io.opentelemetry.api.internal.ValidationUtil.checkValidInstrumentName(ValidationUtil.java:61)
2023-06-05T06:20:35.060967126Z 	at io.opentelemetry.javaagent.shaded.io.opentelemetry.api.metrics.DefaultMeter.counterBuilder(DefaultMeter.java:42)
2023-06-05T06:20:35.060968940Z 	at io.opentelemetry.javaagent.shaded.instrumentation.micrometer.v1_5.OpenTelemetryCounter.<init>(OpenTelemetryCounter.java:36)
2023-06-05T06:20:35.060970953Z 	at io.opentelemetry.javaagent.shaded.instrumentation.micrometer.v1_5.OpenTelemetryMeterRegistry.newCounter(OpenTelemetryMeterRegistry.java:76)
2023-06-05T06:20:35.060972807Z 	at io.micrometer.core.instrument.MeterRegistry.lambda$registerMeterIfNecessary$5(MeterRegistry.java:563)
2023-06-05T06:20:35.060974801Z 	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:618)
2023-06-05T06:20:35.060976574Z 	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:570)
2023-06-05T06:20:35.060978327Z 	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:563)
2023-06-05T06:20:35.060980131Z 	at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:292)
2023-06-05T06:20:35.060981894Z 	at io.micrometer.core.instrument.Counter$Builder.register(Counter.java:131)
2023-06-05T06:20:35.060983668Z 	at io.micrometer.core.instrument.composite.CompositeCounter.registerNewMeter(CompositeCounter.java:49)
2023-06-05T06:20:35.060985451Z 	at io.micrometer.core.instrument.composite.CompositeCounter.registerNewMeter(CompositeCounter.java:23)
2023-06-05T06:20:35.060987385Z 	at io.micrometer.core.instrument.composite.AbstractCompositeMeter.add(AbstractCompositeMeter.java:68)
2023-06-05T06:20:35.060995320Z 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
2023-06-05T06:20:35.060997694Z 	at java.base/java.util.Collections$SetFromMap.forEach(Collections.java:5708)
2023-06-05T06:20:35.060999838Z 	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$0(CompositeMeterRegistry.java:67)
2023-06-05T06:20:35.061003816Z 	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lock(CompositeMeterRegistry.java:189)
2023-06-05T06:20:35.061008325Z 	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$1(CompositeMeterRegistry.java:67)
2023-06-05T06:20:35.061012713Z 	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:627)
2023-06-05T06:20:35.061015769Z 	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:570)
2023-06-05T06:20:35.061017963Z 	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:563)
2023-06-05T06:20:35.061019776Z 	at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:292)
2023-06-05T06:20:35.061021700Z 	at io.micrometer.core.instrument.Counter$Builder.register(Counter.java:131)
2023-06-05T06:20:35.061023484Z 	at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:396)
2023-06-05T06:20:35.061025247Z 	at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:407)
2023-06-05T06:20:35.061026990Z 	at ai.diffy.metrics.MetricsReceiver$MemoizedMetricsReceiver.counter$lzycompute(MetricsReceiver.scala:12)
2023-06-05T06:20:35.061028764Z 	at ai.diffy.metrics.MetricsReceiver$MemoizedMetricsReceiver.counter(MetricsReceiver.scala:12)
2023-06-05T06:20:35.061030527Z 	at ai.diffy.analysis.InMemoryFieldMetadata.<init>(InMemoryDifferenceCollector.scala:32)
2023-06-05T06:20:35.061032521Z 	at ai.diffy.analysis.InMemoryEndpointMetadata.getMetadata(InMemoryDifferenceCollector.scala:62)
2023-06-05T06:20:35.061037751Z 	at ai.diffy.analysis.InMemoryEndpointMetadata.$anonfun$add$3(InMemoryDifferenceCollector.scala:77)
2023-06-05T06:20:35.061039735Z 	at ai.diffy.analysis.InMemoryEndpointMetadata.$anonfun$add$3$adapted(InMemoryDifferenceCollector.scala:76)
2023-06-05T06:20:35.061041558Z 	at scala.collection.immutable.BitmapIndexedMapNode.foreach(HashMap.scala:1076)
2023-06-05T06:20:35.061043341Z 	at scala.collection.immutable.HashMap.foreach(HashMap.scala:1083)
2023-06-05T06:20:35.061045215Z 	at ai.diffy.analysis.InMemoryEndpointMetadata.add(InMemoryDifferenceCollector.scala:76)
2023-06-05T06:20:35.061047079Z 	at ai.diffy.analysis.InMemoryDifferenceCounter.count(InMemoryDifferenceCollector.scala:28)
2023-06-05T06:20:35.061048902Z 	at ai.diffy.analysis.DifferenceAnalyzer.$anonfun$apply$1(DifferenceCollector.scala:61)
2023-06-05T06:20:35.061051367Z 	at scala.Option.flatMap(Option.scala:283)
2023-06-05T06:20:35.061053310Z 	at ai.diffy.analysis.DifferenceAnalyzer.apply(DifferenceCollector.scala:41)
2023-06-05T06:20:35.061055274Z 	at ai.diffy.analysis.DifferenceAnalyzer.analyze(DifferenceCollector.scala:32)
2023-06-05T06:20:35.061059813Z 	at ai.diffy.functional.endpoints.Endpoint.apply(Endpoint.java:28)
2023-06-05T06:20:35.061061797Z 	at ai.diffy.functional.topology.Async.lambda$operator$0(Async.java:22)
2023-06-05T06:20:35.061063640Z 	at ai.diffy.functional.functions.Try.<init>(Try.java:26)
2023-06-05T06:20:35.061065584Z 	at ai.diffy.functional.functions.Try.of(Try.java:11)
2023-06-05T06:20:35.061067477Z 	at ai.diffy.functional.topology.Async.lambda$operator$1(Async.java:22)
2023-06-05T06:20:35.061069231Z 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
2023-06-05T06:20:35.061071004Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
2023-06-05T06:20:35.061072798Z 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
2023-06-05T06:20:35.061074541Z 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
2023-06-05T06:20:35.061076425Z 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
2023-06-05T06:20:35.061078298Z 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2023-06-05T06:20:35.061251562Z [otel.javaagent 2023-06-05 06:20:35:061 +0000] [ForkJoinPool.commonPool-worker-1] WARN io.opentelemetry.ApiUsageLogging - Instrument name "diffy.noise.POST:api-basicInfo.request.path.NoDifference.siblings" is invalid, returning noop instrument. Instrument names must consist of 63 or fewer characters including alphanumeric, _, ., -, and start with a letter.
2023-06-05T06:20:35.061263555Z java.lang.AssertionError
2023-06-05T06:20:35.061267292Z 	at io.opentelemetry.javaagent.shaded.io.opentelemetry.api.internal.ValidationUtil.log(ValidationUtil.java:55)
2023-06-05T06:20:35.061270789Z 	at io.opentelemetry.javaagent.shaded.io.opentelemetry.api.internal.ValidationUtil.checkValidInstrumentName(ValidationUtil.java:72)
2023-06-05T06:20:35.061274286Z 	at io.opentelemetry.javaagent.shaded.io.opentelemetry.api.internal.ValidationUtil.checkValidInstrumentName(ValidationUtil.java:61)
2023-06-05T06:20:35.061277722Z 	at io.opentelemetry.javaagent.shaded.io.opentelemetry.api.metrics.DefaultMeter.counterBuilder(DefaultMeter.java:42)
2023-06-05T06:20:35.061281479Z 	at io.opentelemetry.javaagent.shaded.instrumentation.micrometer.v1_5.OpenTelemetryCounter.<init>(OpenTelemetryCounter.java:36)
2023-06-05T06:20:35.061285307Z 	at io.opentelemetry.javaagent.shaded.instrumentation.micrometer.v1_5.OpenTelemetryMeterRegistry.newCounter(OpenTelemetryMeterRegistry.java:76)
2023-06-05T06:20:35.061289284Z 	at io.micrometer.core.instrument.MeterRegistry.lambda$registerMeterIfNecessary$5(MeterRegistry.java:563)
2023-06-05T06:20:35.061292500Z 	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:618)
2023-06-05T06:20:35.061295687Z 	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:570)
2023-06-05T06:20:35.061299143Z 	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:563)
2023-06-05T06:20:35.061312358Z 	at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:292)
2023-06-05T06:20:35.061316747Z 	at io.micrometer.core.instrument.Counter$Builder.register(Counter.java:131)
2023-06-05T06:20:35.061320834Z 	at io.micrometer.core.instrument.composite.CompositeCounter.registerNewMeter(CompositeCounter.java:49)
2023-06-05T06:20:35.061323540Z 	at io.micrometer.core.instrument.composite.CompositeCounter.registerNewMeter(CompositeCounter.java:23)
2023-06-05T06:20:35.061326135Z 	at io.micrometer.core.instrument.composite.AbstractCompositeMeter.add(AbstractCompositeMeter.java:68)
2023-06-05T06:20:35.061329441Z 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
2023-06-05T06:20:35.061332076Z 	at java.base/java.util.Collections$SetFromMap.forEach(Collections.java:5708)
2023-06-05T06:20:35.061334661Z 	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$0(CompositeMeterRegistry.java:67)
2023-06-05T06:20:35.061337426Z 	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lock(CompositeMeterRegistry.java:189)
2023-06-05T06:20:35.061340923Z 	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$1(CompositeMeterRegistry.java:67)
2023-06-05T06:20:35.061344560Z 	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:627)
2023-06-05T06:20:35.061349910Z 	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:570)
2023-06-05T06:20:35.061354429Z 	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:563)
2023-06-05T06:20:35.061358306Z 	at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:292)
2023-06-05T06:20:35.061361562Z 	at io.micrometer.core.instrument.Counter$Builder.register(Counter.java:131)
2023-06-05T06:20:35.061365389Z 	at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:396)
2023-06-05T06:20:35.061368896Z 	at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:407)
2023-06-05T06:20:35.061372152Z 	at ai.diffy.metrics.MetricsReceiver$MemoizedMetricsReceiver.counter$lzycompute(MetricsReceiver.scala:12)
2023-06-05T06:20:35.061375509Z 	at ai.diffy.metrics.MetricsReceiver$MemoizedMetricsReceiver.counter(MetricsReceiver.scala:12)
2023-06-05T06:20:35.061379336Z 	at ai.diffy.analysis.InMemoryFieldMetadata.<init>(InMemoryDifferenceCollector.scala:33)
2023-06-05T06:20:35.061384666Z 	at ai.diffy.analysis.InMemoryEndpointMetadata.getMetadata(InMemoryDifferenceCollector.scala:62)
2023-06-05T06:20:35.061389215Z 	at ai.diffy.analysis.InMemoryEndpointMetadata.$anonfun$add$3(InMemoryDifferenceCollector.scala:77)
2023-06-05T06:20:35.061393293Z 	at ai.diffy.analysis.InMemoryEndpointMetadata.$anonfun$add$3$adapted(InMemoryDifferenceCollector.scala:76)
2023-06-05T06:20:35.061397411Z 	at scala.collection.immutable.BitmapIndexedMapNode.foreach(HashMap.scala:1076)
2023-06-05T06:20:35.061407169Z 	at scala.collection.immutable.HashMap.foreach(HashMap.scala:1083)
2023-06-05T06:20:35.061411828Z 	at ai.diffy.analysis.InMemoryEndpointMetadata.add(InMemoryDifferenceCollector.scala:76)
2023-06-05T06:20:35.061416567Z 	at ai.diffy.analysis.InMemoryDifferenceCounter.count(InMemoryDifferenceCollector.scala:28)
2023-06-05T06:20:35.061424081Z 	at ai.diffy.analysis.DifferenceAnalyzer.$anonfun$apply$1(DifferenceCollector.scala:61)
2023-06-05T06:20:35.061429271Z 	at scala.Option.flatMap(Option.scala:283)
2023-06-05T06:20:35.061434181Z 	at ai.diffy.analysis.DifferenceAnalyzer.apply(DifferenceCollector.scala:41)
2023-06-05T06:20:35.061438830Z 	at ai.diffy.analysis.DifferenceAnalyzer.analyze(DifferenceCollector.scala:32)
2023-06-05T06:20:35.061443288Z 	at ai.diffy.functional.endpoints.Endpoint.apply(Endpoint.java:28)
2023-06-05T06:20:35.061446264Z 	at ai.diffy.functional.topology.Async.lambda$operator$0(Async.java:22)
2023-06-05T06:20:35.061448187Z 	at ai.diffy.functional.functions.Try.<init>(Try.java:26)
2023-06-05T06:20:35.061450201Z 	at ai.diffy.functional.functions.Try.of(Try.java:11)
2023-06-05T06:20:35.061452075Z 	at ai.diffy.functional.topology.Async.lambda$operator$1(Async.java:22)
2023-06-05T06:20:35.061453848Z 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
2023-06-05T06:20:35.061455672Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
2023-06-05T06:20:35.061457746Z 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
2023-06-05T06:20:35.061461924Z 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
2023-06-05T06:20:35.061466402Z 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
2023-06-05T06:20:35.061471041Z 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2023-06-05T06:20:35.157394102Z 2023-06-05 06:20:35.156  INFO [diffy,,] 1 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : {"t":{"$date":"2023-06-05T06:20:35.156+00:00"},"s":"I",  "c":"STORAGE",  "id":20320,   "ctx":"conn3","msg":"createCollection","attr":{"namespace":"test.differenceResult","uuidDisposition":"generated","uuid":{"uuid":{"$uuid":"c52d6037-6d34-416c-82fd-837f8ec90be4"}},"options":{}}} 
2023-06-05T06:20:35.180059497Z 2023-06-05 06:20:35.179  INFO [diffy,,] 1 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : {"t":{"$date":"2023-06-05T06:20:35.179+00:00"},"s":"I",  "c":"INDEX",    "id":20345,   "ctx":"conn3","msg":"Index build: done building","attr":{"buildUUID":null,"namespace":"test.differenceResult","index":"_id_","commitTimestamp":{"$timestamp":{"t":0,"i":0}}}} 
2023-06-05T06:20:35.185522768Z 2023-06-05 06:20:35.185  INFO [diffy,d14c672776e490b1bfe8c1959b394cd1,4e5f40055409d7c5] 1 --- [onPool-worker-1] ai.diffy.analysis.DifferenceAnalyzer     : repository saved POST:api-basicInfo -- ljBcBGs8at -- d14c672776e490b1bfe8c1959b394cd1 
```

**Comment by puneetkhanduri** [comment]
Fixed in latest docker release.
