### ISSUE TITLE
[Help] start diffy in docker way as described in the docs, but it keep going wrong when sending request to diffy server

### ISSUE THREAD

**Issue by deldong** [opendiffy/diffy#91]
This is my first time using diffy. I followed the steps of the [docker official website ](https://hub.docker.com/r/diffy/example-service) and the steps of the [github document,](https://content.sn126.com/docs/diffy/gettingStarted/DOCKER). All the commands were copied and pasted directly from docs, but still couldn't get the diffy result properly

take docker-example as example, the error is as follows, I changed two PCs and finally got the same error, Could you please help me find out the reason and guide me? thanks!
command: 
```
> docker run -d --name exd-primary -p 9990:5000 diffy/example-service:production
> docker run -d --name exd-secondary -p 9991:5000 diffy/example-service:production
> docker run -d --name exd-candidate -p 9992:5000 diffy/example-service:candidate

# run diffy
> sudo docker run -d --name diffy-docker \
--link exd-candidate:candidate --link exd-primary:primary --link exd-secondary:secondary -p 8880:8880 -p 8881:8881 -p 8888:8888  diffy/diffy \
-candidate=candidate:5000 -master.primary=primary:5000     -master.secondary=secondary:5000 -service.protocol=http -serviceName=Test-Service -proxy.port=:8880     -admin.port=:8881  -http.port=:8888     -rootUrl=localhost:8888

# start sending diffy some data
> curl -s -i -H Canonical-Resource : endpoint-test http://localhost:8880/success?value=happy-tester
> curl -s -i -H Canonical-Resource : endpoint-test http://localhost:8880/noise?value=happy-tester
> curl -s -i -H Canonical-Resource : endpoint-test http://localhost:8880/regression?value=happy-tester
> curl -s -i -H Canonical-Resource : endpoint-test http://localhost:8880/noisy_regression?value=happy-tester
```
<img width="1346" alt="image" src="https://github.com/opendiffy/diffy/assets/13015226/ad1393aa-ffb4-48c7-a2f1-89ad37b723b7">

```2023-06-24 13:17:52.673  INFO [diffy,,] 1 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
2023-06-24 13:17:52.962  INFO [diffy,,] 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 3 endpoint(s) beneath base path '/actuator'
2023-06-24 13:17:53.026  INFO [diffy,,] 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8888 (http) with context path ''
2023-06-24 13:17:53.042  INFO [diffy,,] 1 --- [           main] ai.diffy.Main                            : Started Main in 9.723 seconds (JVM running for 12.111)
2023-06-24 13:18:04.538 ERROR [diffy,1f08be27802a3dbae80a78a34c2fbe61,49347539d1bd0001] 1 --- [onPool-worker-2] a.d.proxy.ReactorHttpDifferenceProxy     : request failed to get response

java.util.concurrent.CompletionException: reactor.core.Exceptions$ReactiveException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:9100
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1097) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[na:na]
	at ai.diffy.functional.topology.Async.lambda$operator$1(Async.java:24) ~[classes!/:1.0.0-SNAPSHOT]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]
Caused by: reactor.core.Exceptions$ReactiveException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:9100
	at reactor.core.Exceptions.propagate(Exceptions.java:396) ~[reactor-core-3.4.22.jar!/:3.4.22]
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97) ~[reactor-core-3.4.22.jar!/:3.4.22]
	at reactor.core.publisher.Mono.block(Mono.java:1707) ~[reactor-core-3.4.22.jar!/:3.4.22]
	at ai.diffy.proxy.HttpEndpoint.lambda$new$6(HttpEndpoint.java:56) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.endpoints.Endpoint.apply(Endpoint.java:28) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.topology.Async.lambda$operator$0(Async.java:22) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.functions.Try.<init>(Try.java:26) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.functions.Try.of(Try.java:11) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.topology.Async.lambda$operator$1(Async.java:22) ~[classes!/:1.0.0-SNAPSHOT]
	... 6 common frames omitted
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.4.22.jar!/:3.4.22]
		... 13 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:9100
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155) ~[netty-transport-native-unix-common-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128) ~[netty-transport-native-unix-common-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:321) ~[netty-transport-native-unix-common-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710) ~[netty-transport-classes-epoll-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687) ~[netty-transport-classes-epoll-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[netty-transport-classes-epoll-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:477) ~[netty-transport-classes-epoll-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[netty-transport-classes-epoll-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-06-24 13:18:04.544  INFO [diffy,1f08be27802a3dbae80a78a34c2fbe61,49347539d1bd0001] 1 --- [onPool-worker-2] a.d.proxy.ReactorHttpDifferenceProxy     :
2023-06-24 13:18:04.547 ERROR [diffy,1f08be27802a3dbae80a78a34c2fbe61,49347539d1bd0001] 1 --- [onPool-worker-2] r.n.http.server.HttpServerOperations     : [fd263775-1, L:/172.17.0.5:8880 - R:/172.17.0.1:38396] Error starting response. Replying error status

reactor.core.Exceptions$ReactiveException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:9100
	at reactor.core.Exceptions.propagate(Exceptions.java:396) ~[reactor-core-3.4.22.jar!/:3.4.22]
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97) ~[reactor-core-3.4.22.jar!/:3.4.22]
	at reactor.core.publisher.Mono.block(Mono.java:1707) ~[reactor-core-3.4.22.jar!/:3.4.22]
	at ai.diffy.proxy.HttpEndpoint.lambda$new$6(HttpEndpoint.java:56) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.endpoints.Endpoint.apply(Endpoint.java:28) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.topology.Async.lambda$operator$0(Async.java:22) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.functions.Try.<init>(Try.java:26) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.functions.Try.of(Try.java:11) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.topology.Async.lambda$operator$1(Async.java:22) ~[classes!/:1.0.0-SNAPSHOT]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.4.22.jar!/:3.4.22]
		... 13 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:9100
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155) ~[netty-transport-native-unix-common-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128) ~[netty-transport-native-unix-common-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:321) ~[netty-transport-native-unix-common-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710) ~[netty-transport-classes-epoll-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687) ~[netty-transport-classes-epoll-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[netty-transport-classes-epoll-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:477) ~[netty-transport-classes-epoll-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[netty-transport-classes-epoll-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

[otel.javaagent 2023-06-24 13:18:06:581 +0000] [OkHttp http://localhost:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4317
[otel.javaagent 2023-06-24 13:18:41:490 +0000] [OkHttp http://localhost:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4317```

**Comment by deldong** [comment]
tried Jar based the doc [Using diffy Jar](https://content.sn126.com/docs/diffy/gettingStarted/JAR), got the errors below:
```
2023-06-24 15:43:20.206  INFO [diffy,,] 115907 --- [or-http-epoll-2] a.d.proxy.ReactorHttpDifferenceProxy     :
2023-06-24 15:43:20.207 ERROR [diffy,,] 115907 --- [or-http-epoll-2] r.n.http.server.HttpServerOperations     : [9da5989c-1, L:/0:0:0:0:0:0:0:1%0:8880 - R:/0:0:0:0:0:0:0:1%0:49054] Error starting response. Replying error status

java.lang.NoSuchMethodError: 'java.util.List java.util.stream.Stream.toList()'
	at ai.diffy.proxy.HttpMessage.lambda$group$1(HttpMessage.java:31) ~[classes!/:1.0.0-SNAPSHOT]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at ai.diffy.proxy.HttpMessage.group(HttpMessage.java:30) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.proxy.HttpMessage.<init>(HttpMessage.java:16) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.proxy.HttpRequest.<init>(HttpRequest.java:20) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.proxy.HttpEndpoint.lambda$static$0(HttpEndpoint.java:39) ~[classes!/:1.0.0-SNAPSHOT]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[na:na]
	at reactor.core.publisher.MonoToCompletableFuture.onComplete(MonoToCompletableFuture.java:84) ~[reactor-core-3.4.22.jar!/:3.4.22]
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:220) ~[reactor-core-3.4.22.jar!/:3.4.22]
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:275) ~[reactor-core-3.4.22.jar!/:3.4.22]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:128) ~[reactor-core-3.4.22.jar!/:3.4.22]
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:208) ~[reactor-core-3.4.22.jar!/:3.4.22]
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[reactor-core-3.4.22.jar!/:3.4.22]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[reactor-core-3.4.22.jar!/:3.4.22]
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:129) ~[reactor-core-3.4.22.jar!/:3.4.22]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.4.22.jar!/:3.4.22]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.4.22.jar!/:3.4.22]
	at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.4.22.jar!/:3.4.22]
	at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:161) ~[reactor-netty-core-1.0.22.jar!/:1.0.22]
	at reactor.netty.channel.FluxReceive.lambda$subscribe$2(FluxReceive.java:146) ~[reactor-netty-core-1.0.22.jar!/:1.0.22]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[netty-transport-classes-epoll-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.79.Final.jar!/:4.1.79.Final]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

2023-06-24 15:43:59.681 ERROR [diffy,,] 115907 --- [onPool-worker-3] a.d.proxy.ReactorHttpDifferenceProxy     : request failed to get response

java.util.concurrent.CompletionException: java.lang.RuntimeException: Content-Type : application/x-www-form-urlencoded is not supported
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1099) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235) ~[na:na]
	at ai.diffy.functional.topology.Async.lambda$contain$4(Async.java:46) ~[classes!/:1.0.0-SNAPSHOT]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
Caused by: java.lang.RuntimeException: Content-Type : application/x-www-form-urlencoded is not supported
	at ai.diffy.proxy.HttpEndpoint.lambda$static$1(HttpEndpoint.java:30) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.endpoints.Endpoint.apply(Endpoint.java:28) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.topology.Async.lambda$contain$3(Async.java:44) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.functions.Try.<init>(Try.java:26) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.functions.Try.of(Try.java:11) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.topology.Async.lambda$contain$4(Async.java:44) ~[classes!/:1.0.0-SNAPSHOT]
	... 6 common frames omitted

2023-06-24 15:43:59.682  INFO [diffy,,] 115907 --- [onPool-worker-3] a.d.proxy.ReactorHttpDifferenceProxy     :
2023-06-24 15:43:59.682 ERROR [diffy,,] 115907 --- [onPool-worker-3] r.n.http.server.HttpServerOperations     : [d1b0c071-1, L:/0:0:0:0:0:0:0:1%0:8880 - R:/0:0:0:0:0:0:0:1%0:54154] Error starting response. Replying error status

java.lang.RuntimeException: Content-Type : application/x-www-form-urlencoded is not supported
	at ai.diffy.proxy.HttpEndpoint.lambda$static$1(HttpEndpoint.java:30) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.endpoints.Endpoint.apply(Endpoint.java:28) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.topology.Async.lambda$contain$3(Async.java:44) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.functions.Try.<init>(Try.java:26) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.functions.Try.of(Try.java:11) ~[classes!/:1.0.0-SNAPSHOT]
	at ai.diffy.functional.topology.Async.lambda$contain$4(Async.java:44) ~[classes!/:1.0.0-SNAPSHOT]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
```

**Comment by deldong** [comment]
close this issue as the latest jar works fine except for clear all data
